In [1]:
import torch
import helper

In [2]:
x = torch.rand(3,2)
x

tensor([[0.4549, 0.2608],
        [0.6063, 0.5567],
        [0.1791, 0.8764]])

In [3]:
y = torch.ones(x.size())
y

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [15]:
y_x = torch.empty(3,5)
y_x

tensor([[ 0.0000,  0.0000, 25.6750,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000]])

In [4]:
y.mul_(2) #multiply tensors by 2

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [5]:
#First neural network with pytorch
from torchvision import datasets, transforms

In [6]:
transform = transforms.Compose([transforms.ToTensor(),
                                transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))])

In [7]:
trainset = datasets.MNIST('MNIST_data/',download=True, train=True
                         )

In [8]:
type(x)

torch.Tensor

In [9]:
x = x.numpy()
x

array([[ 0.45485097,  0.26077861],
       [ 0.60626054,  0.55668247],
       [ 0.17907059,  0.87641293]], dtype=float32)

In [10]:
type(x)

numpy.ndarray

In [11]:
x = torch.from_numpy(x)

In [12]:
type(x)

torch.Tensor

In [16]:
x = torch.tensor([[1, -1],[5, 7]])
x

tensor([[ 1, -1],
        [ 5,  7]])

In [28]:
x = x.new_ones(5,3, dtype= torch.double)
x, x.size(), x.type()

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]], dtype=torch.float64),
 torch.Size([5, 3]),
 'torch.DoubleTensor')